import aenum


class Cmd(aenum.Constant):
    GPCAMERA_SETTING = '/setting/{}/{}'
    GPCAMERA_SHUTTER = '/command/shutter?p={}'
    GPCAMERA_MODE = '/command/mode?p={}'
    GPCAMERA_SUBMODE = '/command/sub_mode?mode={}&sub_mode={}'
    GPCAMERA_POWER_ID = '/command/system/sleep'
    GPCAMERA_FWUPDATE_DOWNLOAD_START = '/command/fwupdate/download/start'
    GPCAMERA_FWUPDATE_DOWNLOAD_DONE = '/command/fwupdate/download/done'
    GPCAMERA_FWUPDATE_DOWNLOAD_CANCEL = '/command/fwupdate/download/cancel'
    GPCAMERA_FACTORY_RESET = '/command/system/factory/reset'
    GPCAMERA_SLEEP = '/command/system/sleep'
    GPCAMERA_USE_CURRENT_WIRELESS_REMOTE_ID = '/setting/63/2'
    GPCAMERA_USE_NEW_WIRELESS_REMOTE_ID = '/command/wireless/rc/pair'
    GPCAMERA_CANCEL_PAIR_WIRELESS_REMOTE_ID = '/command/wireless/rc/pair/cancel'
    GPCAMERA_CANCEL_PAIR_WIRELESS_ID = '/command/wireless/pair/cancel'
    GPCAMERA_VIDEO_PROTUNE_RESET_TO_DEFAULT = '/command/video/protune/reset'
    GPCAMERA_MULTISHOT_PROTUNE_RESET_TO_DEFAULT = '/command/multi_shot/protune/reset'
    GPCAMERA_PHOTO_PROTUNE_RESET_TO_DEFAULT = '/command/photo/protune/reset'
    GPCAMERA_SET_DATE_AND_TIME_ID = '/command/setup/date_time'
    GPCAMERA_DELETE_LAST_FILE_ID = '/command/storage/delete/last'
    GPCAMERA_DELETE_ALL_FILES_ID = '/command/storage/delete/all'
    GPCAMERA_DELETE_FILE_ID = '/command/storage/delete?p={}'
    GPCAMERA_LOCATE_ID = '/command/system/locate'
    GPCAMERA_NETWORK_NAME_ID = '/command/wireless/ap/ssid'
    GPCAMERA_AP_CONTROL = '/command/wireless/ap/control'
    GPCAMERA_INFO_VERSION_ID = 'camera_version'
    GPCAMERA_NETWORK_VERSION_ID = 'bacpac_version'
    GPCAMERA_BATTERY_LEVEL_ID = 'camera_battery'
    GPCAMERA_SDCARD_CAPACITY_ID = 'sd_card'
    GPCAMERA_TAG_MOMENT = '/command/storage/tag_moment'
    GPCAMERA_RC_PAIR = '/command/rc/pair'
    GPCAMERA_SSID_SCAN = '/command/wireless/ssid/scan'
    GPCAMERA_SSID_LIST = '/command/wireless/ssid/list'
    GPCAMERA_SSID_SELECT = '/command/wireless/ssid/select'
    GPCAMERA_SSID_DELETE = '/command/wireless/ssid/delete'
