import enum


class Settings(enum.Enum):
    VIDEO_SUB_MODE = 68
    VIDEO_RESOLUTION = 2
    VIDEO_FRAME_RATE = 3
    VIDEO_FOV = 4

    TIMELAPSE_VIDEO_INTERVAL = 5
    LOOPING_VIDEO_INTERVAL = 6
    PHOTO_VIDEO_INTERVAL = 7

    VIDEO_LOW_LIGHT = 8
    VIDEO_SPOT_METER = 9
    VIDEO_PROTUNE = 10
    VIDEO_WHITE_BALANCE = 11
    VIDEO_COLOR = 12
    VIDEO_ISO_LIMIT = 13
    VIDEO_SHARPNESS = 14
    VIDEO_EV_COMP = 15

    PHOTO_SUB_MODE = 69
    PHOTO_MEGAPIXEL = 17
    PHOTO_CONTINUOUS_RATE = 18
    PHOTO_SHUTTER = 19
    PHOTO_SPOT_METER = 20
    PHOTO_PROTUNE = 21
    PHOTO_WHITE_BALANCE = 22
    PHOTO_COLOR = 23
    PHOTO_ISO_LIMIT = 24
    PHOTO_SHARPNESS = 25
    PHOTO_EV_COMP = 26

    MULTISHOT_SUB_MODE = 70
    MULTISHOT_DEFAULT_SUB_MODE = 27
    MULTISHOT_NIGHT_SHUTTER_EXPOSURE = 31
    MULTISHOT_BURST_RATE = 29
    MULTISHOT_TIMELAPSE_INTERVAL = 30
    MULTISHOT_NIGHTLAPSE_INTERVAL = 32
    MULTISHOT_MEGAPIXEL = 28
    MULTISHOT_SPOT_METER = 33
    MULTISHOT_PROTUNE = 34
    MULTISHOT_WHITE_BALANCE = 35
    MULTISHOT_COLOR = 36
    MULTISHOT_SHARPNESS = 38
    MULTISHOT_EV_COMP = 39
    MULTISHOT_ISO_LIMIT = 37

    LCD_DISPLAY = 72
    ORIENTATION = 52
    DEFAULT_BOOT_MODE = 53
    QICK_CAPTURE = 54
    LED_STATUS = 55
    BEEP_VOLUME = 56
    VIDEO_FORMAT = 57
    ON_SCREEN_DATA = 58
    AUTO_POWER_OFF = 59